workflows:
    react-native-android:
        name: React Native 
        max_build_duration: 120
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: master
                  include: true
                  source: true
         scripts:
                - docker build -t apache  .

