workflows:
  tests:
    scripts:
      - name: Install pyenv
        script: |
          brew install pyenv
      - name: Install dependencies
        script: |
          python3 -m pip install --upgrade pip pipenv
          pipenv install --dev
