workflows:
  tests:
    scripts:
      - name: Install pyenv
        script: |
          export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
          brew install pyenv
      - name: Install dependencies
        script: |
          python3 -m pip install --upgrade pip pipenv
          pipenv install --dev
